<a href="https://colab.research.google.com/github/Esha-Sherring/Data-Science-summer-analytica/blob/master/numpy_pandas_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
numbers 1,2,3
string 'Hello'
List [1,2,3,4]
Tuple (1,2)
Dictionary {1: 'VAlue',2:'value 2'}


In [ ]:
a=5
b=6
c=a+b
print(c)

11


In [ ]:
x='HEllo'
y='World'
print(x+y)


HElloWorld


In [ ]:
print(x[1])

E


In [ ]:
x[1:4]

'Ell'

In [ ]:
[1,2,3]

[1, 2, 3]

In [ ]:
['a',2,3]

['a', 2, 3]

In [ ]:
my_list = ['a','b','c']

In [ ]:
my_list[0] = 'e'

In [ ]:
my_list

['e', 'b', 'c']

In [ ]:
mylist=['a',['b','c']]

In [ ]:
mylist[1][0]

'b'

In [ ]:
d={'name':'aryan','rollno':103834,'branch':'computer'}
print(d)
print(d['name'])

{'name': 'aryan', 'rollno': 103834, 'branch': 'computer'}
aryan


In [ ]:
d.values()


dict_values(['fe', 'sfwe'])

In [ ]:
t = (1,2,3,4,5)
print(t[0])

1


In [ ]:
t[0] = 34

TypeError: ignored

In [ ]:
1>2

False

In [ ]:
print(1<2)
print(3>=3)
print(2==3)
print(2!=2)


True
True
False
False


In [ ]:
print('bla'=='bla')

True


In [ ]:
print((1>2)and(2<4))
print((1>2)or(2<4))

False
True


In [ ]:
if 1<1:
  print("aueu")
elif 2>1:
  print("svsdv")
else:
  print("tyutyu")

svsdv


In [ ]:

a=5
b=6
c=2
if a>b and a>c:
    print('a is greater')
elif b>c and b>a:
    print('b is greater')
else:
    print('c is greater') 

b is greater


In [ ]:
var = ['a',1,2,3,0.5]
for item in var:
  print(item)
  

a
1
2
3
0.5


In [ ]:
for i in range(2,5,2):
  print(var[i])

2
0.5


In [ ]:
range(5)


range(0, 5)

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
i=1
while i<5:
  print(i)
  i=i+1

1
2
3
4


In [ ]:
x=[1,2,3,4,5]
out=[]
for item in  x:
  out.append(item**2)
print(out)

[1, 4, 9, 16, 25]


In [ ]:
[item**2 for item in x]

[1, 4, 9, 16, 25]

In [ ]:
a = int(input('input a value'))
print(a+4)

input a value10
14


In [ ]:
i=[0,1]
x=0
for x in range(10):
  i.append(i[x]+i[x+1])
  x=x+1
print(i)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


In [ ]:
def bleh():
  print('kjsghjsrgjhrfg')

bleh()
def bleh1(a,b):
  print(a+b)
bleh1(3,6)
def bleh2(a,b):
  return a+b
c = bleh2(23,56)
print(c)

kjsghjsrgjhrfg
9
79


In [ ]:
def largest(a,b,c):
  if a>b and a>c:
    print('a is greater')
  elif b>c and b>a:
    print('b is greater')
  else:
    print('c is greater')

largest(3,7,2) 

b is greater


In [ ]:
s = 'Hello#World#siknge'
print(s.lower())
print(s.upper())
a = s.split('#')
print(a[1])

hello#world#siknge
HELLO#WORLD#SIKNGE
World


In [ ]:
def fib(n):
  if n==1 or n==0 :
    return n
  else:
    return fib(n-1) + fib(n-2)

i = 0
for n in range(8):
  print(fib(n))

0
1
1
2
3
5
8
13


In [ ]:
 import numpy as np

In [ ]:
lis = [1,2,3,4]
np.array(lis)

array([1, 2, 3, 4])

In [ ]:
lis

[1, 2, 3, 4]

In [ ]:
matrix = [[1,2,3],[2,3,4]]
np.array(matrix)

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
# build in methods
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
a = np.ones((5),float)
b = "hsdikfd"
print(a.shape)
print(type(a))
print(type(b))

(5,)
<class 'numpy.ndarray'>
<class 'str'>


In [ ]:
# random Function
a = np.random.randint(1,20,(5,4))
print(a)
print('------------')
print(a[2:4,0])
c = a[2:5,0]
c[:] = 99
print(c)
print('------------')
print(a)
print(a.reshape(4,5))

[[11 13  1  7]
 [16 18  1 17]
 [19 12 16  8]
 [19  5  2 16]
 [ 3  4 15  7]]
------------
[19 19]
[99 99 99]
------------
[[11 13  1  7]
 [16 18  1 17]
 [99 12 16  8]
 [99  5  2 16]
 [99  4 15  7]]
[[11 13  1  7 16]
 [18  1 17 99 12]
 [16  8 99  5  2]
 [16 99  4 15  7]]


In [ ]:
np.random.randint(1,100,10)

array([65, 96, 36, 28, 56, 65, 56, 83, 71, 10])

In [ ]:
import pandas as pd
a = np.random.randint(1,20,5)
lab = ['a','b','c','d','e']
s = pd.Series(a,index=lab)
print(s['a'])

4


In [ ]:
#https://bit.ly/2S7aRKS

a = np.random.randint(1,20,(5,5))
print(a.shape)
lab = ['a','b','c','d','e']
lab2 = ['a1','b1','c1','d1','e1']
s = pd.DataFrame(a,index=lab2,columns=lab)
print(s)
print('-----------')
print(s[['a','c']])
s.drop('a',axis=1,inplace=True)
print('----------')
print(s)
print(s.iloc[2,2])

(5, 5)
     a   b   c   d   e
a1   3   2   3  13   1
b1  14  14  10   1   5
c1   4  19   4   5  17
d1   6   7  14  14   4
e1   7  15  16   4   6
-----------
     a   c
a1   3   3
b1  14  10
c1   4   4
d1   6  14
e1   7  16
----------
     b   c   d   e
a1   2   3  13   1
b1  14  10   1   5
c1  19   4   5  17
d1   7  14  14   4
e1  15  16   4   6
5
